renderNav('hobbies');
window.goBT=id=>{document.querySelectorAll('.bt-page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.bt-btn').forEach(b=>b.classList.remove('active'));document.getElementById('bt-'+id).classList.add('active');document.querySelector('.bt-btn[onclick="goBT(\''+id+'\')"]').classList.add('active');window.scrollTo(0,0)};
function bR(c,k){const el=document.getElementById(c);if(!el)return;const items=ls(k,[]);el.innerHTML='';if(!items.length){el.innerHTML='<div style="text-align:center;padding:.5rem;color:var(--tmut);font-size:10px;font-style:italic;opacity:.7">Nothing yet</div>';return}items.forEach((t,i)=>{const txt=typeof t==='string'?t:t.text||'';const e=document.createElement('div');e.className='bi';e.innerHTML='<span style="flex:1">'+txt+'</span><button class="bi-del" onclick="bD(\''+c+'\',\''+k+'\','+i+')">×</button>';el.appendChild(e)})}
window.bA=(c,iid,k)=>{const inp=document.getElementById(iid);if(!inp)return;const v=inp.value.trim();if(!v)return;const items=ls(k,[]);items.push(v);ss(k,items);inp.value='';bR(c,k)};
window.bD=(c,k,i)=>{const items=ls(k,[]);items.splice(i,1);ss(k,items);bR(c,k)};
const ALL=[['mk-eyes','wh_makeup_eyes'],['mk-lips','wh_makeup_lips'],['mk-face','wh_makeup_face'],['mk-log','wh_makeup_looks'],['mk-inspo','wh_makeup_inspo'],['mk-tuts','wh_makeup_tutorials'],['mk-wish','wh_makeup_wishlist'],['hr-products','wh_hair_products'],['hr-log','wh_hair_styles'],['hr-inspo','wh_hair_inspo'],['hr-tuts','wh_hair_tutorials'],['hr-wish','wh_hair_wishlist'],['of-log','wh_outfit_log'],['of-inspo','wh_outfits_inspo'],['of-loves','wh_wardrobe_loves'],['of-wish','wh_outfits_wishlist'],['nl-log','wh_nails_log'],['nl-polish','wh_nails_polishes'],['nl-inspo','wh_nails_inspo'],['nl-tuts','wh_nails_tutorials'],['nl-wish','wh_nails_wishlist']];
ALL.forEach(([c,k])=>bR(c,k));
document.getElementById('hr-notes').value=ls('wh_hair_notes','')||'';
document.getElementById('of-notes').value=ls('wh_wardrobe_notes','')||'';
